export AWWW_TRANSITION_FPS="60"
export AWWW_TRANSITION_STEP="90"
export AWWW_TRANSITION_POS="0.8,0.66"
export AWWW_TRANSITION_ANGLE="33"
export AWWW_TRANSITION="grow"
DEFAULT_INTERVAL=300 # In seconds
RESIZE="crop"
